#!/usr/bin/python
import BaseHTTPServer
import logging
from optparse import OptionParser
import socket
import ssl
import traceback
import urlparse
from vesna import alh

log = logging.getLogger(__name__)

class HTTPRequestHandler(BaseHTTPServer.BaseHTTPRequestHandler):
	def __init__(self, alh, *args, **kwargs):
		self.alh = alh
		BaseHTTPServer.BaseHTTPRequestHandler.__init__(self, *args, **kwargs)

	def _error(self, status, message):
		self.send_response(status)
		self.send_header("Content-type", "text/plain")
		self.end_headers()
		self.wfile.write(message)

	def do_GET_unsafe(self):
		parsed = urlparse.urlparse(self.path)

		if parsed.path != '/communicator':
			self._error(404, "Path not found: %s" % (parsed.path,))
			return

		query = urlparse.parse_qs(parsed.query)

		method = query['method'][0].lower()
		resource = query['resource'][0]

		if method == 'get':
			try:
				resp = self.alh.get(resource)
			except alh.ALHException, e:
				resp = str(e)
		elif method == 'post':
			data = query['content'][0]
			try:
				resp = self.alh.post(resource, data)
			except alh.ALHException, e:
				resp = str(e)
		else:
			self._error(400, "Invalid method: %s" % (method,))
			return

		self.send_response(200)
		self.send_header("Content-type", "text/plain")
		self.end_headers()
		self.wfile.write(resp)

	def do_GET(self):
		try:
			self.do_GET_unsafe()
		except Exception:
			self._error(500, traceback.format_exc())

class HTTPRequestHandlerFactory:
	def __init__(self, handler_class, alh):
		self.alh = alh
		self.handler_class = handler_class

	def __call__(self, *args, **kwargs):
		o = self.handler_class(self.alh, *args, **kwargs)
		return o

def main():
	parser = OptionParser(usage="%prog [options]")

	parser.add_option("--key", dest="keyfile", metavar="PATH", default="key.pem",
			help="Path to the private key")
	parser.add_option("--cert", dest="certfile", metavar="PATH", default="cert.pem",
			help="Path to the certificate")

	parser.add_option("-o", "--http-port", dest="httpport", metavar="PORT", type="int", default=8000,
			help="Port to listen on for HTTP traffic")
	parser.add_option("-i", "--tunnel-port", dest="sslport", metavar="PORT", type="int", default=9501,
			help="Port to listen on for SSH tunel from coordinator")

	(options, args) = parser.parse_args()

	logging.basicConfig(level=logging.INFO)

	bindsocket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
	bindsocket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
	#bindsocket.setsockopt(socket.SOL_TCP, socket.TCP_MAXSEG, 536)
	bindsocket.setsockopt(socket.SOL_TCP, socket.TCP_NODELAY, 1)
	bindsocket.bind(('', options.sslport))
	bindsocket.listen(5)

	logging.info("Listening on port %d" % (options.sslport,))

	while True:
		newsocket, fromaddr = bindsocket.accept()

		logging.info("Received connection from %s" % (fromaddr,))

		connstream = ssl.wrap_socket(newsocket, 
				server_side=True, 
				cert_reqs=ssl.CERT_NONE,
				certfile=options.certfile,
				keyfile=options.keyfile,
				ssl_version=ssl.PROTOCOL_TLSv1)
		try:
			alht = alh.ALHTerminal(connstream)
			alht.RETRIES = 1

			f = HTTPRequestHandlerFactory(HTTPRequestHandler, alht)
			httpd = BaseHTTPServer.HTTPServer(('', options.httpport), f)
			httpd.serve_forever()
		finally:
			connstream.shutdown(socket.SHUT_RDWR)
			connstream.close()

main()
