#!/usr/bin/python
from alh import alh
from alh import common
import datetime
from optparse import OptionParser
import sys

class NodeInfo: 
	def __init__(self):
		self.hello = None
		self.firstcall = None
		self.uptime = None

def query_node(node):
	nodeinfo = NodeInfo()

	try:
		nodeinfo.hello = node.get("hello").strip()
		nodeinfo.firstcall = node.get("prog/firstcall").strip()
		nodeinfo.uptime = float(node.get("uptime").strip())
	except:
		nodeinfo.ok = False
	else:
		if nodeinfo.hello:
			nodeinfo.hello = nodeinfo.hello.replace(
					"Hello Application version ", "")

		if nodeinfo.firstcall:
			nodeinfo.firstcall = nodeinfo.firstcall.replace(
					"firstCallFlag is ", "")

		if nodeinfo.uptime:
			nodeinfo.uptime = datetime.timedelta(seconds=nodeinfo.uptime-1325376000.0)

		nodeinfo.ok = True

	return nodeinfo

def get_neigbors(node):
	try:
		#node.post("prog/firstcall", "1")
		r = node.get("radio/neighbors")
	except Exception, e:
		print "Failed:", e
		return

	for line in r.split("\r\n"):
		fields = line.split(" | ")
		if len(fields) == 6:
			try:
				yield int(fields[3])
			except ValueError:
				pass

def print_stats(visited):
	visited = sorted((id, info) for id, info in visited.iteritems())

	print "ID\tOnline\tVersion\tF.call\tUptime"
	for id, info in visited:
		row = [	
			id,
			info.ok,
			info.hello,
			info.firstcall,
			info.uptime,
		]

		print '\t'.join(map(str, row))


def main():
	parser = OptionParser(usage="%prog [options]")

	common.add_communication_options(parser)

	parser.add_option("-o", "--output", dest="output", metavar="PATH",
			help="PATH to write dotfile to")

	(options, args) = parser.parse_args()

	coordinator = common.get_coordinator(options)	

	queue = [0]
	visited = {}

	if options.output:
		outf = open(options.output, "w")
	else:
		outf = sys.stdout

	outf.write("digraph net {\n")

	n = 0
	while queue:
		current_id = queue.pop()
		if current_id not in visited:
			print "*** Query node ID:", current_id

			if current_id == 0:
				node = coordinator
			else:
				node = alh.ALHProxy(coordinator, current_id)

			nodeinfo = query_node(node)
			visited[current_id] = nodeinfo

			if nodeinfo.ok:
				for next_id in get_neigbors(node):
					outf.write("n%d -> n%d\n" % (current_id, next_id))
					queue.insert(0, next_id)
	
	outf.write("}\n")

	print_stats(visited)

main()
